dist: bionic
language: python
python:
  - 3.7

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - docker --version
  - make docker-image

script:
  - make run-tests-e2e SEEDSYNC_VERSION=latest
