dist: bionic
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker pull ubuntu:16.04 ubuntu:18.04 ubuntu:20.04 node:12.16 yukinying/chrome-headless-browser-selenium:latest alpine:3.11.6

install:
  - docker --version
  - make docker-image

script:
  - make run-tests-e2e SEEDSYNC_VERSION=latest
