version: "3.4"
services:

  test:
    build: ../tests/e2e
    volumes:
      - type: bind
        source: ../../e2e
        target: /e2e
        read_only: true

  chrome:
    build: ../chrome
    shm_size: 1024M
    cap_add:
     - SYS_ADMIN

  myapp:
    build:
      context: ../install
    tty: true
    tmpfs:
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ${PATH_TO_INSTALL_DEB}
        target: /install/seedsync.deb
        read_only: true

      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true

  remote:
    build: ../remote
