version: "3.4"
services:

  test:
    build: ../tests/e2e
    volumes:
      - type: bind
        source: ../../e2e
        target: /e2e
        read_only: true

  chrome:
    build: ../chrome
    shm_size: 1024M
    cap_add:
     - SYS_ADMIN

  remote:
    build: ../remote
