version: "3.4"
services:
  test:
    build: ../tests/python
    volumes:
      - type: bind
        source: ../../python
        target: /src
        read_only: true

      - type: bind
        source: /tmp
        target: /tmp
